package de.nordwind.schulungsplaner.service;

import java.util.Arrays;

public enum Benachrichtigungsanlass {
    TRAINERZUWEISUNG_GESETZT,
    TRAINERZUWEISUNG_BEENDET,
    ROLLENWECHSEL,
    TERMIN_GEAENDERT,
    TERMIN_ABGESAGT,
    TERMIN_GELOESCHT,
    TERMIN_AUTOMATISCH_ABGESCHLOSSEN,
    QUALIFIKATION_GENEHMIGT,
    QUALIFIKATION_ABGELEHNT,
    QUALIFIKATION_DURCH_ARCHIVIERUNG_ENTFALLEN,
    QUALIFIKATION_DIREKT,
    QUALIFIKATION_ENTZOGEN,
    QUALIFIKATION_ABGELEGT,
    VORMERKUNG_BESTAETIGT,
    VORMERKUNG_ABGELEHNT,
    VORMERKUNG_DURCH_ZUWEISUNG_ENTFALLEN,
    ASSISTENZBEWERBUNG_ENTSCHIEDEN,
    UEBERNAHMEANFRAGE_ENTSCHIEDEN,
    UEBERNAHMEANFRAGE_DURCH_TAUSCH_ENTFALLEN,
    TRAINERWECHSEL_DURCH_UEBERNAHME,
    ABWESENHEITSANTRAG_ABGELEHNT,
    ABWESENHEITSANTRAG_MANUELL_GENEHMIGT,
    ABWESENHEITSANTRAG_NACH_FRIST_GENEHMIGT,
    ERSATZTRAINER_ANFRAGE_BEENDET,
    VERFUEGBARKEITSKONFLIKT_DURCH_ABWESENHEIT,
    VORGANG_DURCH_TERMINENDE_ANGEPASST_ODER_ENTFALLEN,
    VORGANG_DURCH_KONTOENDE_ENTFALLEN;

    public static Benachrichtigungsanlass von(String wert) {
        return Arrays.stream(values()).filter(anlass -> anlass.name().equals(wert)).findFirst()
                .orElseThrow(() -> new IllegalArgumentException(
                        "Unbekannter Benachrichtigungsanlass: " + wert));
    }
}
