CREATE TABLE IF NOT EXISTS benutzerkonto (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    passwort_hash VARCHAR(100) NOT NULL,
    aktiv BOOLEAN NOT NULL DEFAULT TRUE,
    aenderungsstand BIGINT NOT NULL DEFAULT 0,
    passwort_version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS benutzerkonto_rolle (
    benutzerkonto_id VARCHAR(36) NOT NULL,
    rolle VARCHAR(30) NOT NULL CHECK (rolle IN ('TRAINER', 'ADMINISTRATOR')),
    PRIMARY KEY (benutzerkonto_id, rolle),
    CONSTRAINT fk_rolle_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS instanz (
    id INT PRIMARY KEY CHECK (id = 1),
    eigentuemer_id VARCHAR(36),
    CONSTRAINT fk_instanz_eigentuemer FOREIGN KEY (eigentuemer_id)
        REFERENCES benutzerkonto(id)
);

INSERT INTO instanz (id, eigentuemer_id)
SELECT 1, NULL WHERE NOT EXISTS (SELECT 1 FROM instanz WHERE id = 1);

-- Die Beschreibung einer Schulung liegt im versionierten Katalog. Die
-- Datenbank hält nur ihren veränderlichen Zustand.
CREATE TABLE IF NOT EXISTS schulung_zustand (
    schulung_id VARCHAR(50) PRIMARY KEY,
    zustand VARCHAR(20) NOT NULL,
    archiviert_am DATE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_schulung_zustand CHECK (zustand IN ('AKTIV', 'ARCHIVIERT'))
);

CREATE TABLE IF NOT EXISTS abwesenheit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benutzerkonto_id VARCHAR(36) NOT NULL,
    von DATE NOT NULL,
    bis DATE NOT NULL,
    grund VARCHAR(255),
    CONSTRAINT fk_abwesenheit_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);
ALTER TABLE abwesenheit ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'AKTIV';

CREATE TABLE IF NOT EXISTS trainer_qualifikation (
    benutzerkonto_id VARCHAR(36) NOT NULL,
    schulung_id VARCHAR(50) NOT NULL,
    PRIMARY KEY (benutzerkonto_id, schulung_id),
    CONSTRAINT fk_qualifikation_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE,
    CONSTRAINT fk_qualifikation_schulung FOREIGN KEY (schulung_id)
        REFERENCES schulung_zustand(schulung_id)
);

CREATE TABLE IF NOT EXISTS qualifikationsbewerbung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benutzerkonto_id VARCHAR(36),
    schulung_id VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OFFEN',
    erstellt_am TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    entschieden_am TIMESTAMP,
    begruendung VARCHAR(1000),
    antragsteller_name VARCHAR(255),
    CONSTRAINT uq_qualifikationsbewerbung UNIQUE (benutzerkonto_id, schulung_id),
    CONSTRAINT fk_qualifikationsbewerbung_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE SET NULL,
    CONSTRAINT fk_qualifikationsbewerbung_schulung FOREIGN KEY (schulung_id)
        REFERENCES schulung_zustand(schulung_id)
);

ALTER TABLE qualifikationsbewerbung
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'OFFEN';
ALTER TABLE qualifikationsbewerbung ADD COLUMN IF NOT EXISTS entschieden_am TIMESTAMP;
ALTER TABLE qualifikationsbewerbung ADD COLUMN IF NOT EXISTS begruendung VARCHAR(1000);
ALTER TABLE qualifikationsbewerbung ADD COLUMN IF NOT EXISTS antragsteller_name VARCHAR(255);
ALTER TABLE qualifikationsbewerbung ALTER COLUMN benutzerkonto_id DROP NOT NULL;
ALTER TABLE qualifikationsbewerbung DROP CONSTRAINT IF EXISTS fk_qualifikationsbewerbung_konto;
ALTER TABLE qualifikationsbewerbung ADD CONSTRAINT fk_qualifikationsbewerbung_konto
    FOREIGN KEY (benutzerkonto_id) REFERENCES benutzerkonto(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS vorgang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    art VARCHAR(40) NOT NULL,
    antragsteller_id VARCHAR(36),
    antragsteller_name VARCHAR(255) NOT NULL,
    zustaendig_id VARCHAR(36),
    zustaendig_rolle VARCHAR(30),
    bezug_art VARCHAR(20) NOT NULL,
    bezug_id VARCHAR(80) NOT NULL,
    bezug VARCHAR(255) NOT NULL,
    von DATE,
    bis DATE,
    status VARCHAR(40) NOT NULL DEFAULT 'OFFEN',
    erstellt_am TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    entschieden_am TIMESTAMP,
    entschieden_von_id VARCHAR(36),
    entschieden_von_name VARCHAR(255),
    begruendung VARCHAR(1000),
    CONSTRAINT fk_vorgang_antragsteller FOREIGN KEY (antragsteller_id)
        REFERENCES benutzerkonto(id) ON DELETE SET NULL,
    CONSTRAINT fk_vorgang_zustaendig FOREIGN KEY (zustaendig_id)
        REFERENCES benutzerkonto(id) ON DELETE SET NULL,
    CONSTRAINT fk_vorgang_entscheider FOREIGN KEY (entschieden_von_id)
        REFERENCES benutzerkonto(id) ON DELETE SET NULL
);

-- Termine dürfen nach dem Löschen einer Schulung bestehen bleiben.
CREATE TABLE IF NOT EXISTS termin (
    termin_id VARCHAR(80) PRIMARY KEY,
    schulung_id VARCHAR(50) NOT NULL,
    startdatum DATE NOT NULL,
    enddatum DATE NOT NULL,
    ort VARCHAR(255),
    format VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    trainer_id VARCHAR(36),
    trainer_name_snapshot VARCHAR(255),
    schulung_titel VARCHAR(255),
    CONSTRAINT fk_termin_trainer FOREIGN KEY (trainer_id)
        REFERENCES benutzerkonto(id)
);

ALTER TABLE termin ADD COLUMN IF NOT EXISTS zugangsart VARCHAR(20);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS trainer_name_snapshot VARCHAR(255);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS schulung_titel VARCHAR(255);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS durchfuehrungsart VARCHAR(30);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS kundenfirma VARCHAR(255);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS online_zugang VARCHAR(1000);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS abschlussart VARCHAR(20);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS abgeschlossen_am DATE;
ALTER TABLE termin ADD COLUMN IF NOT EXISTS bestaetigt_von VARCHAR(36);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS abgesagt_am DATE;
ALTER TABLE termin ADD COLUMN IF NOT EXISTS abgesagt_von VARCHAR(36);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS absagegrund VARCHAR(1000);
ALTER TABLE termin ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE termin ALTER COLUMN ort DROP NOT NULL;
UPDATE termin SET status='geplant' WHERE status='ausgebucht';
ALTER TABLE termin ADD CONSTRAINT IF NOT EXISTS ck_termin_status
    CHECK (status IN ('geplant', 'abgeschlossen', 'abgesagt'));

CREATE TABLE IF NOT EXISTS termin_nummer (
    schulung_id VARCHAR(50) PRIMARY KEY,
    naechste_nummer INT NOT NULL CHECK (naechste_nummer BETWEEN 1 AND 10000)
);

CREATE TABLE IF NOT EXISTS termin_assistent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termin_id VARCHAR(80) NOT NULL,
    benutzerkonto_id VARCHAR(36),
    name_snapshot VARCHAR(255),
    platz SMALLINT NOT NULL CHECK (platz BETWEEN 1 AND 3),
    CONSTRAINT uq_termin_assistent UNIQUE (termin_id, benutzerkonto_id),
    CONSTRAINT uq_termin_assistent_platz UNIQUE (termin_id, platz),
    CONSTRAINT fk_assistent_termin FOREIGN KEY (termin_id)
        REFERENCES termin(termin_id) ON DELETE CASCADE,
    CONSTRAINT fk_assistent_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id)
);

CREATE TABLE IF NOT EXISTS assistenzbewerbung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termin_id VARCHAR(80) NOT NULL,
    benutzerkonto_id VARCHAR(36) NOT NULL,
    erstellt_am TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_assistenzbewerbung UNIQUE (termin_id, benutzerkonto_id),
    CONSTRAINT fk_assistenzbewerbung_termin FOREIGN KEY (termin_id)
        REFERENCES termin(termin_id) ON DELETE CASCADE,
    CONSTRAINT fk_assistenzbewerbung_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vormerkung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termin_id VARCHAR(80) NOT NULL,
    benutzerkonto_id VARCHAR(36) NOT NULL,
    CONSTRAINT fk_vormerkung_termin FOREIGN KEY (termin_id)
        REFERENCES termin(termin_id) ON DELETE CASCADE,
    CONSTRAINT fk_vormerkung_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS benachrichtigung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empfaenger_id VARCHAR(36),
    empfaenger_rolle VARCHAR(30),
    anlasstyp VARCHAR(80) NOT NULL DEFAULT 'BESTAND',
    anlass VARCHAR(255) NOT NULL,
    bezug_art VARCHAR(30),
    bezug_id VARCHAR(80),
    erstellt_am TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gelesen BOOLEAN NOT NULL DEFAULT FALSE,
    gelesen_am TIMESTAMP,
    CONSTRAINT ck_benachrichtigung_empfaenger CHECK (
        (empfaenger_id IS NOT NULL AND empfaenger_rolle IS NULL)
        OR (empfaenger_id IS NULL AND empfaenger_rolle = 'ADMINISTRATOR')
    ),
    CONSTRAINT fk_benachrichtigung_konto FOREIGN KEY (empfaenger_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);

ALTER TABLE benachrichtigung ALTER COLUMN anlass VARCHAR(2000);
ALTER TABLE benachrichtigung ALTER COLUMN empfaenger_id DROP NOT NULL;
ALTER TABLE benachrichtigung ADD COLUMN IF NOT EXISTS empfaenger_rolle VARCHAR(30);
ALTER TABLE benachrichtigung ADD COLUMN IF NOT EXISTS anlasstyp VARCHAR(80) NOT NULL DEFAULT 'BESTAND';
ALTER TABLE benachrichtigung ADD COLUMN IF NOT EXISTS bezug_art VARCHAR(30);
ALTER TABLE benachrichtigung ADD COLUMN IF NOT EXISTS bezug_id VARCHAR(80);
ALTER TABLE benachrichtigung ADD COLUMN IF NOT EXISTS gelesen_am TIMESTAMP;

CREATE TABLE IF NOT EXISTS teilnehmerbuchung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termin_id VARCHAR(80) NOT NULL,
    name VARCHAR(255),
    firma VARCHAR(255) NOT NULL,
    bemerkung VARCHAR(1000),
    teilnahmestatus VARCHAR(30) NOT NULL DEFAULT 'offen',
    CONSTRAINT ck_teilnahmestatus CHECK
        (teilnahmestatus IN ('offen', 'teilgenommen', 'nicht_teilgenommen')),
    CONSTRAINT fk_buchung_termin FOREIGN KEY (termin_id)
        REFERENCES termin(termin_id) ON DELETE CASCADE
);
