CREATE TABLE IF NOT EXISTS benutzerkonto (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    passwort_hash VARCHAR(100) NOT NULL,
    aktiv BOOLEAN NOT NULL DEFAULT TRUE,
    aenderungsstand BIGINT NOT NULL DEFAULT 0,
    passwort_version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS benutzerkonto_rolle (
    benutzerkonto_id VARCHAR(36) NOT NULL,
    rolle VARCHAR(30) NOT NULL CHECK (rolle IN ('TRAINER', 'ADMINISTRATOR')),
    PRIMARY KEY (benutzerkonto_id, rolle),
    CONSTRAINT fk_rolle_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS instanz (
    id INT PRIMARY KEY CHECK (id = 1),
    eigentuemer_id VARCHAR(36),
    CONSTRAINT fk_instanz_eigentuemer FOREIGN KEY (eigentuemer_id)
        REFERENCES benutzerkonto(id)
);

INSERT INTO instanz (id, eigentuemer_id)
SELECT 1, NULL WHERE NOT EXISTS (SELECT 1 FROM instanz WHERE id = 1);

CREATE TABLE IF NOT EXISTS schulung (
    id VARCHAR(50) PRIMARY KEY,
    titel VARCHAR(255) NOT NULL,
    kategorie VARCHAR(255) NOT NULL,
    kurzbeschreibung CLOB NOT NULL,
    dauer_in_tagen INT NOT NULL,
    mindestteilnehmer_exklusiv INT NOT NULL,
    max_teilnehmer_oeffentlich INT
);

CREATE TABLE IF NOT EXISTS voraussetzung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schulung_id VARCHAR(50) NOT NULL,
    text VARCHAR(500) NOT NULL,
    CONSTRAINT fk_voraussetzung_schulung FOREIGN KEY (schulung_id)
        REFERENCES schulung(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS abwesenheit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benutzerkonto_id VARCHAR(36) NOT NULL,
    von DATE NOT NULL,
    bis DATE NOT NULL,
    grund VARCHAR(255),
    CONSTRAINT fk_abwesenheit_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS trainer_qualifikation (
    benutzerkonto_id VARCHAR(36) NOT NULL,
    schulung_id VARCHAR(50) NOT NULL,
    PRIMARY KEY (benutzerkonto_id, schulung_id),
    CONSTRAINT fk_qualifikation_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE,
    CONSTRAINT fk_qualifikation_schulung FOREIGN KEY (schulung_id)
        REFERENCES schulung(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS qualifikationsbewerbung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benutzerkonto_id VARCHAR(36) NOT NULL,
    schulung_id VARCHAR(50) NOT NULL,
    erstellt_am TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_qualifikationsbewerbung UNIQUE (benutzerkonto_id, schulung_id),
    CONSTRAINT fk_qualifikationsbewerbung_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE,
    CONSTRAINT fk_qualifikationsbewerbung_schulung FOREIGN KEY (schulung_id)
        REFERENCES schulung(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS termin (
    termin_id VARCHAR(80) PRIMARY KEY,
    schulung_id VARCHAR(50) NOT NULL,
    startdatum DATE NOT NULL,
    enddatum DATE NOT NULL,
    ort VARCHAR(255) NOT NULL,
    format VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    trainer_id VARCHAR(36),
    trainer_name_snapshot VARCHAR(255),
    CONSTRAINT fk_termin_schulung FOREIGN KEY (schulung_id)
        REFERENCES schulung(id),
    CONSTRAINT fk_termin_trainer FOREIGN KEY (trainer_id)
        REFERENCES benutzerkonto(id)
);

CREATE TABLE IF NOT EXISTS termin_assistent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termin_id VARCHAR(80) NOT NULL,
    benutzerkonto_id VARCHAR(36),
    name_snapshot VARCHAR(255),
    platz SMALLINT NOT NULL CHECK (platz BETWEEN 1 AND 3),
    CONSTRAINT uq_termin_assistent UNIQUE (termin_id, benutzerkonto_id),
    CONSTRAINT uq_termin_assistent_platz UNIQUE (termin_id, platz),
    CONSTRAINT fk_assistent_termin FOREIGN KEY (termin_id)
        REFERENCES termin(termin_id) ON DELETE CASCADE,
    CONSTRAINT fk_assistent_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id)
);

CREATE TABLE IF NOT EXISTS assistenzbewerbung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termin_id VARCHAR(80) NOT NULL,
    benutzerkonto_id VARCHAR(36) NOT NULL,
    erstellt_am TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_assistenzbewerbung UNIQUE (termin_id, benutzerkonto_id),
    CONSTRAINT fk_assistenzbewerbung_termin FOREIGN KEY (termin_id)
        REFERENCES termin(termin_id) ON DELETE CASCADE,
    CONSTRAINT fk_assistenzbewerbung_konto FOREIGN KEY (benutzerkonto_id)
        REFERENCES benutzerkonto(id) ON DELETE CASCADE
);
